apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voooice

commonLabels:
  app.kubernetes.io/part-of: vocaltext
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - secrets.yaml
  - frontend.yaml
  - backend.yaml
  - tts.yaml
  - ingress.yaml
